const Joi = require("joi");
const mongoose = require("mongoose");

const MedicalHistory = mongoose.model("MedicalHistory", new mongoose.Schema({
   currentSymptoms:{
       type:String
   },
   currentMedicalHistory:{
       diagnosis:{
           type:String
       },
       diagnosisDate:{
           type:Date
       },
       treatment:{
           type:String
       },
       prescription:{
           type:String
       },
       investigationReport:{
           type:String
       }
   },
   allergies:{
        dust:{
            type:String
        },
        pollen:{
            type:String
        },
        medication:{
            type:String
        },
        food:{
            type:String
        },
        other:{
            type:String
        }
    },
    pastMedicalHistory:{
        diagnosis:{
            type:String
        },
        diagnosisDate:{
            type:Date
        },
        treatment:{
            type:String
        },
        status:{
            type:String
        },
        prescription:{
            type:String
        },
        investigationReport:{
            type:String
        }
    },
    previousSurgeries: {
        diagnosis:{
            type:String
        },
        diagnosisDate:{
            type:Date
        },
        status:{
            type:String
        },
        prescription:{
            type:String
        },
        investigationReport:{
            type:String
        }
    },
    previousTreatment: {
        diagnosis:{
            type:String
        },
        diagnosisDate:{
            type:Date
        },
        treatment:{
            type:String
        },
        status:{
            type:String
        },
        prescription:{
            type:String
        },
        investigationReport:{
            type:String
        }
    },
    FamilyMedicalHistory: {
        diagnosis:{
            type:String
        },
        diagnosisDate:{
            type:Date
        },
        relationship:{
            type:String
        },
        status:{
            type:String
        }
    },
    menustrualHistory:{
        menarche:{
            type:String
        },
        lmp:{
            type:String
        },
        Frequency:{
            type:String
        },
        duration:{
            type:String
        },
        flow:{
            type:String
        },
        cramps:{
            type:String
        },
        menopause:{
            type:Date
        }
    },
    childBirthHistory:{
        ageofChild:{
            type:Number
        },
        sexofChild:{
            type:String
        },
        modeOfDelivery:{
            type:String
        },
        complications:{
            type:String
        },
        abortions:{
            count:{
                type:{
                    Number
                }
            },
            longestDuration:{
                type:String
            },
            modeOfTermination:{
                type:String
            }
        }
    },
    recentInvestigation:{
        type:String
    },
    userId:{
        type:String
    }
  })
);




module.exports.MedicalHistory = MedicalHistory;
